サインアップ機能初回コミット
shinonome-inc/-backend-final-assignment-Mizuki pull request #1
Opened 2023-05-24 11:48 UTC by ChibaMizuki

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-05-26 03:33 UTC, takano630 commented
すいませんローカル環境で稼働確認しようとしたんですけどうまくいかなかったので、実行画面のスクショとか送ってほしいです。
testは確認ました！！
<img width="393" alt="image" src="https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/83489580/6387265a-be17-47e0-8848-371e0df8ece7">

2023-05-26 10:02 UTC, ChibaMizuki commented
1枚目：正しいフォーム入力
2枚目：入力後の移行ページ
3枚目：空欄のフォーム
4枚目：ユーザーネーム空欄時
5枚目：メールアドレス空欄時
6枚目：パスワード空欄時
7枚目：登録済みユーザーネーム入力時
8枚目：短いパスワード入力時
9枚目：ユーザーネーム酷似パスワード入力時
10枚目：数字パスワード入力時
11枚目：パスワード不一致時
12枚目：不適切なメールアドレス入力時

テスト要項に記載のあるエラーは出しました。
最初にサイトを訪れた時にサインアップフォームに飛ばすような設定にできてないためうまく稼働できない感じでしょうか？
もしそうならそのあたりのコードも変えたほうがいいですか？


![Sign Up - Google Chrome 2023_05_26 18_31_04](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/129958367/8aca033e-d738-46d2-8e26-609e9ab258b8)
![Sign Up - Google Chrome 2023_05_26 18_31_17](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/129958367/5ccfed0b-fab8-4ccc-9f9f-8fc3816cdd23)
![Sign Up - Google Chrome 2023_05_26 18_31_49](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/129958367/1012a124-abd8-4f6c-93eb-8be685ad3f2e)
![Sign Up - Google Chrome 2023_05_26 18_32_40](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/129958367/33e580ad-ed96-414a-9b1c-7a6dabacb59c)
![Sign Up - Google Chrome 2023_05_26 18_33_01](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/129958367/678c1558-1f60-4b07-a8cb-0d643ad9a02d)
![Sign Up - Google Chrome 2023_05_26 18_33_34](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/129958367/b451ea2c-0884-44d7-b8e7-355f040daac7)
![Sign Up - Google Chrome 2023_05_26 18_33_57](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/129958367/15b8e6e8-e943-4bfc-afbc-b4bc4ec57ec6)
![Sign Up - Google Chrome 2023_05_26 18_35_33](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/129958367/842c8a8c-f7db-4a92-b1db-b824c7cc5bb0)
594f5)
![Sign Up - Google Chrome 2023_05_26 18_36_06](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/129958367/c973da42-5cf3-4b5d-bf79-b884a7b79f76)
![Sign Up - Google Chrome 2023_05_26 18_36_36](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/129958367/30d428f0-7f16-40fa-98e6-6dd8c165d09c)
![Sign Up - Google Chrome 2023_05_26 18_37_21](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/129958367/9c8f54ca-d13d-474b-a9bf-9786c4b79486)
![Sign Up - Google Chrome 2023_05_26 18_34_24](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/129958367/548b4890-d913-4dd4-a320-5344a1e2570c)

2023-05-28 02:35 UTC, takano630 commented
その通りでした...見落としてましたすいません
写真ありがとうございます！！
最終課題テスト項目要件の画面と機能のとこ見る感じ「welcomeview」の機能とかどの時点で作るとか書いてないんですけどsignupに飛べる画面とかがあったほうがいいのかなぁとは思いました！！！

2023-05-28 02:36 UTC, takano630 commented
LGTMです

2023-05-28 12:14 UTC, sui-false requested changes
現在のコードではadmin画面がないので、それも作りましょう。
admin側でどのユーザーが登録できているのかを確認するためです。

2023-05-28 12:14 UTC, sui-false commented on accounts/tests.py
> +    def test_failure_post_with_empty_email(self):
DBに追加されていないかのテストを追加しましょう

2023-05-28 12:14 UTC, sui-false commented on accounts/tests.py
> +    def test_failure_post_with_empty_password(self):
DBに追加されていないかのテストを追加しましょう

2023-05-28 12:14 UTC, sui-false commented on accounts/tests.py
> +    def test_failure_post_with_duplicated_user(self):
ここも、DBに追加されていないかのテストを追加しましょう

2023-05-28 12:14 UTC, sui-false commented on accounts/tests.py
> +    def test_failure_post_with_invalid_email(self):
ここも同様です

2023-05-28 12:14 UTC, sui-false commented on accounts/tests.py
> +    def test_failure_post_with_too_short_password(self):
ここも

2023-05-28 12:14 UTC, sui-false commented on accounts/tests.py
> +    def test_failure_post_with_password_similar_to_username(self):
ここもお願いします！

2023-05-28 12:14 UTC, sui-false commented on accounts/tests.py
> +    def test_failure_post_with_only_numbers_password(self):
ここもですね

2023-05-28 12:14 UTC, sui-false commented on accounts/tests.py
> +    def test_failure_post_with_mismatch_password(self):
ここもお願いしますー

2023-06-01 23:55 UTC, sui-false approved these changes

2023-06-01 23:55 UTC, merged