ツイート機能の実装
shinonome-inc/-backend-final-assignment-Mizuki pull request #3
Opened 2023-08-06 01:51 UTC by ChibaMizuki

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-08-09 09:50 UTC, h-iwasaki083 reviewed
遅くなりました🙇‍♀️数点ご確認お願いします！
テストの書き方が丁寧でとても良いと思います💮

2023-08-09 09:50 UTC, h-iwasaki083 commented on tweets/tests.py
> +        self.assertEqual(User.objects.count(), first_count + 1)
`Tweet.objects.count()` かな？

2023-08-09 09:50 UTC, h-iwasaki083 commented on tweets/tests.py
> +        self.assertEqual(response.status_code, 302)
確認していることが99行目と同じように見えるので、なくて大丈夫です◎

2023-08-09 09:50 UTC, h-iwasaki083 commented on tweets/views.py
> +        return super().get_queryset().select_related("user")
関数ごと上書きしなくても、queryset変数だけを上書きしてあげれば良さそうです👀
ListViewのデフォルトではqueryset変数は `queryset=none` となっているので、そこに全ての投稿を格納してあげる処理を書きましょう！

参考資料：[ccbv](https://ccbv.co.uk/projects/Django/4.2/django.views.generic.list/ListView/#get_queryset)
![image](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/113806290/05bb19db-0d6b-4897-a091-f0a4c93f1f42)

2023-08-09 09:50 UTC, h-iwasaki083 commented on tweets/views.py
> +        return super().get_queryset().select_related("user")
こちらに関してはソースコードを見ると、`queryset=none` の場合はモデルが指定されていればそこからオブジェクトを持ってこられるので、get_queryset関数をオーバーライドする必要はなさそうです！👌

![image](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/113806290/864bf77d-c96e-4b8b-a45d-c5b6163968ef)

2023-08-09 09:50 UTC, h-iwasaki083 commented on tweets/views.py
> +        return super().get_queryset().select_related("user")
こちらに関してはソースコードを見ると、`queryset=none` の場合はモデルが指定されていればそこからオブジェクトを持ってこられるので、get_queryset関数をオーバーライドする必要はなさそうです！👌

![image](https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/113806290/5b3e0af0-c02f-43b7-86e9-9ac1809432ef)

2023-08-12 15:40 UTC, h-iwasaki083 approved these changes
修正内容確認しました！
1次レビューOKです◎

2023-08-12 15:40 UTC, h-iwasaki083 commented on mysite/settings.py
> +SQL_DEBUG = True
レビュワーがテストを走らせるときに大量のエラーが出てしまうので、ここはN+1を確認するとき以外はFalseにしておいて下さい👀

2023-08-13 05:23 UTC, sui-false requested changes
全体的によく書けていると思います。
細かな点のみ、修正お願いします。

2023-08-13 05:23 UTC, sui-false commented on tweets/views.py
> +    context_object_name = "Delete"
現時点ではツイートしか存在しませんが、他に削除できるオブジェクトを作成した際に名称がややこしいことになるので、Tweet_deleteのようにした方が親切かもしれません。

2023-08-13 05:23 UTC, sui-false commented on tweets/views.py
> +    context_object_name = "detail"
Deleteと同様です。

2023-08-13 05:23 UTC, sui-false commented on templates/tweets/detail.html
> +        <p>{{detail.user}} {{detail.created_at}}</p>
detail画面のユーザー名からもprofileへ飛べるようにしましょう

2023-08-13 05:23 UTC, sui-false commented on templates/tweets/detail.html
> +    <div style="padding: 10px; margin-bottom: 10px; border: 1px solid #333333; background-color: #191976; color: #ffffff;">
これはtweet全般に言えることですが、投稿本文は白字で読みやすいですが、ボタンが読みにくいです。
ボタンの文字色の変更をするか、背景色を変えた方が無難かもしれません

2023-08-15 09:40 UTC, sui-false approved these changes

2023-08-15 09:41 UTC, merged