初回フォロー機能実装
shinonome-inc/-backend-final-assignment-Mizuki pull request #4
Opened 2023-09-15 05:15 UTC by ChibaMizuki

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-09-17 02:55 UTC, h-iwasaki083 commented on accounts/models.py
> +    following = models.ForeignKey(User, related_name="following", on_delete=models.CASCADE)
Userモデルを直接インポートするのではなく、settings.pyで定義したAUTH_USER_MODELをインポートして使いましょう！プロジェクト全体で参照するUserモデルに一貫性をもたせるために有用です◎

2023-09-17 02:55 UTC, h-iwasaki083 commented on accounts/models.py
> +class FriendShip(models.Model):
Friendshipモデルのフィールドに関して、

- [ ] フォローされるひとのフィールド名は、followingよりfolloweeの方が分かり易くなるのかなと思います🤔
- [ ] フォロー関係が作成されたタイムスタンプを残すために、created_atフィールドの作成をお願いします！

2023-09-18 15:19 UTC, h-iwasaki083 reviewed
テスト以外の部分に関してコメントしました！ご確認お願いします◎

2023-09-18 15:19 UTC, h-iwasaki083 commented on accounts/views.py
> +        context["user"] = user
昨日BootCampでざっと話した内容と被りますが、

31行目でmodel変数を上書きしたことによりuserのオブジェクトは取って来ることができていて、context_object_nameを指定することでprofileという名前でオブジェクトをテンプレートに渡すことができます。
そのため、userの中身をあえてコンテキストとする必要はなく、テンプレートでuserを用いているところに関してはprofileで代替することが出来ます◎

2023-09-18 15:19 UTC, h-iwasaki083 commented on accounts/views.py
> +        user = get_object_or_404(User, username=self.kwargs["username"])
プロフィールページがgetで呼ばれることで呼び出されるget_object関数の中では、以下の画像のような処理が走っています。
（パッと見てなるほど！ってなるものじゃないね… 40行目までがslugに入っているユーザーネームを DB内のユーザーネームに紐づけてクエリを取り出してくる処理、41行目以降が万が一slugに存在しないユーザーネームが入りプロフィールページが表示できない場合の処理）

この41行目以降の処理で、もしobjectが取って来られない場合に404エラーを出す処理が実装されています。そのため、改めてget_object_or_404を用いてobjectが取って来られない場合を考慮する必要はないです◎

<img width="517" alt="image" src="https://github.com/shinonome-inc/-backend-final-assignment-Mizuki/assets/113806290/0180eff8-66ea-4136-abc6-5672702d7474">

2023-09-18 15:19 UTC, h-iwasaki083 commented on accounts/views.py
> +        return redirect("tweets:home")
56行目、58行目でそれぞれreturnが使われていて、if文に入っていた場合そこで処理終わっているので63行目も60, 61行目と同じインデントで良いかも？

2023-09-18 15:19 UTC, h-iwasaki083 commented on accounts/views.py
> +        context["following_list"] = FriendShip.objects.filter(follower=following).select_related("following")
フィルター掛けのところで follower = following となってると結構ややこしくなってしまうので、88行目は変数名userとかにしてしまってもいいかもしれないです◎

2023-09-18 15:19 UTC, h-iwasaki083 commented on accounts/views.py
> +        context["follower_list"] = FriendShip.objects.filter(following=follower).select_related("follower")
ここも同様

2023-09-18 15:19 UTC, h-iwasaki083 commented on templates/accounts/profile.html
> +    <p>(´・ω・)</p>
可愛いっ(´・ω・)

2023-09-22 04:05 UTC, h-iwasaki083 commented on accounts/tests.py
> +        self.url = reverse("accounts:follow", kwargs={"username": "testuser2"})
これ以下いくつかのテストコードで共通なのですが、setUp以外での変数にはself.は付けなくて良いです。
selfをつけるのは、そのメソッド外でも使いたい時です。今回はこのメソッド内で使えればいいので変数名は url で大丈夫です◎

2023-09-23 11:13 UTC, h-iwasaki083 approved these changes
1次レビューOKです！！

2023-09-26 15:02 UTC, gaato requested changes
全体的によく書けています！２点だけコメントしました！

2023-09-26 15:02 UTC, gaato commented on templates/accounts/following_list.html
> +        {% endfor %}
これ表示しようとするとエラーが出ます．
ヒント：`following` か `followee` に統一しよう（エラーの原因はここだけど View も）

2023-09-26 15:02 UTC, gaato commented on templates/accounts/profile.html
> +    </form>
ただのページ遷移には CSRF Token は要らないです．そもそも form じゃなくても良いです．
他のボタンも同様．（Django のフォームを使っているところは CSRF Token は必要です）

2023-09-29 04:04 UTC, gaato requested changes

2023-09-29 04:04 UTC, gaato commented on templates/tweets/home.html
> +</form>
こことその下のやつもお願いします！
（他にもあるけど今回の範囲外なので修正しなくても良いです）

2023-09-30 02:46 UTC, ChibaMizuki commented on templates/tweets/home.html
> +</form>
前回に修正すべきところ、確認不足ですみませんでした
もしよろしければ他はどこを修正すべきか教えていただけないでしょうか？

2023-10-01 02:19 UTC, gaato commented on templates/tweets/home.html
> +</form>
すみません，見間違いでした！OK です！

2023-10-01 02:20 UTC, gaato approved these changes

2023-10-01 02:21 UTC, merged